baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Práctica Hugo - Irene Sanz'
theme = 'book'

# Multi-lingual mode config
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[languages.es]
  languageName = 'Español'
  contentDir = 'content.es'
  weight = 2

[languages.fr]
  languageName = 'Français'
  contentDir = 'content.fr'
  weight = 3


# Menu de debajo
[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/sbirene"
  weight = 10

[[menu.after]]
  name = "Hugo Themes"
  url = "https://themes.gohugo.io/hugo-book/"
  weight = 20

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = false

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = '004-lapiz.png'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'docs'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/sbirene/practicaHugo_DWES_2DAW.git'

  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'J2 January 2006'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = false

  # (Optional, default true) Enables comments template on pages
  # By default partials/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments = false